// This file is auto-generated

import Foundation

enum LocKey: String {
    case access_revoked_sign_in_required
    case account
    case account_has_been_successfully_recovered
    case account_id
    case account_id_or_email_colon
    case acknowledgements
    case address_is_copied_to_pasteboard
    case already_have_an_account
    case aml_alert_request
    case amount
    case amount_colon
    case amount_newline
    case amount_newline_replace_base
    case amount_sent
    case annual_return
    case app_name
    case are_you_sure_you_want_to_cancel_investment
    case are_you_sure_you_want_to_cancel_pending_offer
    case are_you_sure_you_want_to_sign_out
    case ask_base
    case ask_base_replace_base
    case asset
    case asset_balance_is_not_found
    case asset_colon
    case asset_colon_replace_code
    case asset_details
    case asset_pair
    case asset_summary
    case assets
    case at_date
    case at_date_replace_date
    case authenticator
    case available
    case available_amount
    case available_amount_replace_amount
    case available_colon
    case available_assets_for_this_operations
    case available_date
    case available_date_replace_formatted
    case back
    case balance_colon
    case balance_is_not_created
    case balance_is_not_created_replace_asset
    case balances
    case bank_account
    case bank_address
    case bank_address_colon
    case bank_name
    case bank_name_colon
    case base_asset_for_hard_cap
    case base_for_price
    case base_for_price_replace_base_amount
    case base_for_price_replace_price_amount
    case bid_base
    case bid_base_replace_base
    case bought
    case bounds
    case buy
    case can_be_traded_on_secondary_market
    case can_be_transfered
    case can_be_withdrawn
    case cancel
    case cancel_investment
    case cancel_pending_offer
    case cancel_tfa
    case canceled
    case cannot_be_traded_on_secondary_market
    case cannot_be_transfered
    case cannot_be_withdrawn
    case cannot_decode_original_account_id_data
    case cannot_derive_encoded_wallet_id
    case card_holder
    case card_number
    case card_number_colon
    case card_owner
    case change_password
    case charged
    case charged_from_lock
    case chart
    case chart_cap
    case check_sale_state
    case choose_asset
    case choose_email
    case close_time
    case code
    case confirm
    case confirm_new_password
    case confirm_password
    case confirm_password_lowercased
    case confirmation
    case contacts
    case continue_capitalized
    case copied
    case copy
    case corrupted_keychain_data
    case create_balance
    case create_order
    case credit_card
    case cvv
    case dashboard
    case date
    case day
    case days_to_go
    case days_to_go_replace_days
    case days_to_start
    case days_to_start_replace_days
    case default_capitalized
    case deployed
    case deposit
    case deposit_to
    case description
    case description_optional
    case destination_address
    case destination_address_colon
    case details
    case details_days_to_go
    case details_days_to_go_replace_days
    case details_days_to_start
    case details_days_to_start_replace_days
    case details_invested
    case details_invested_replace_amount
    case details_starts_in_days
    case details_starts_in_days_replace_days
    case document_max_size
    case document_max_size_replace_file_size
    case done
    case dont_have_an_account
    case effect
    case email
    case email_address_is_not_verified
    case email_already_taken
    case email_lowercased
    case empty_amount
    case empty_recipient_address
    case empty_signers_data
    case ended
    case enter_account_holders_name
    case enter_account_id_or_email
    case enter_amount
    case enter_bank_address
    case enter_bank_name
    case enter_card_holders_name
    case enter_card_number
    case enter_destination_address
    case enter_email
    case enter_f
    case enter_f_replace_field_name
    case enter_first_name
    case enter_iban
    case enter_last_name
    case enter_password
    case enter_password_confirmation
    case enter_recovery_seed
    case enter_swift_bic
    case enter_t
    case enter_t_replace_title
    case erase_all_data_and
    case error
    case error_while_formatting_orderbookid
    case expected_revenue
    case expires_at
    case expires_at_replace_date
    case export_seed
    case failed
    case failed_to_build_kdf_params
    case failed_to_build_transaction
    case failed_to_cancel_investment
    case failed_to_create_balance_for
    case failed_to_create_balance_for_replace_asset
    case failed_to_decode_account_id
    case failed_to_decode_account_id_replace_id
    case failed_to_decode_asset_details
    case failed_to_decode_balance_id
    case failed_to_decode_balance_id_replace_id
    case failed_to_decode_base_balance_id
    case failed_to_decode_quote_balance_id
    case failed_to_encode_destination_address
    case failed_to_encode_destination_data
    case failed_to_fetch_fees
    case failed_to_fetch_network_info
    case failed_to_generate_key_pair
    case failed_to_generate_new_key_pair
    case failed_to_generate_password_factor_key_pair
    case failed_to_generate_recovery_key_pair
    case failed_to_get_wallet_data
    case failed_to_load_fees
    case failed_to_load_fees_replace_message
    case failed_to_prepare_transaction
    case failed_to_resolve_recipient_address
    case failed_to_resolve_recipient_address_replace_message
    case failed_to_save_account_data
    case failed_to_save_key_and_wallet_data
    case failed_to_save_network_info
    case failed_to_scan_server_info
    case fatal_error
    case fee
    case fee_error
    case fee_error_replace_message
    case fees
    case first_name
    case fixed
    case fixed_colon
    case fixed_fee
    case for_code
    case for_code_replace_code
    case forgot_your_password
    case formatted_date
    case formatted_date_replace_date
    case from
    case from_replace_amount
    case from_account
    case from_to
    case from_to_replace_lower
    case from_to_replace_upper
    case funded
    case funded_lowercase
    case general
    case get_address
    case goal
    case goal_replace_amount
    case go_to_confirmation
    case hard_cap
    case holders_name_colon
    case hour
    case i_agree_on_the
    case i_understand
    case iban
    case iban_colon
    case id_document
    case in_asset
    case in_asset_replace_asset
    case incoming
    case incoming_outgoing
    case incorrect_or_corrupted_recovery_seed
    case input_2fa_code
    case input_code_from_google_authenticator_or_similar_app
    case input_code_sent_to_your_email
    case input_password
    case install_authenticator
    case insufficient_funds
    case invalid_account_id
    case invalid_account_id_or_email
    case invest
    case invest_cap
    case invest_help
    case invest_help_message
    case invested
    case invested_replace_amount
    case investing
    case investing_in_own_sale_is_forbidden
    case investment
    case investment_cancellation
    case investment_details
    case investment_to_be_cancelled_is_not_found
    case investments
    case investors
    case investors_replace_count
    case is_not_restricted_by_current_price
    case is_not_restricted_by_physical_price
    case is_restricted_by_current_price
    case is_restricted_by_physical_price
    case issuance
    case issued
    case keychaindataprovider_should_always_provide_key
    case last_name
    case loading
    case locked
    case lower_bound
    case main_title
    case manage_asset_pair
    case matched
    case maturity_date
    case maximum
    case mm_yy
    case month
    case more_info
    case movements
    case network_info_error
    case network_info_error_replace_message
    case never
    case new_password
    case new_password_lowercased
    case next
    case no_asks
    case no_asset
    case no_assets
    case no_assets_can_be_deposited
    case no_available_periods
    case no_balance
    case no_balances
    case no_bids
    case no_chart_entries
    case no_contacts_available
    case no_fees
    case no_fees_to_overview
    case no_growth
    case no_investments
    case no_movements
    case no_open_sales
    case no_opportunities
    case no_payments
    case no_pending_orders
    case no_personal_address
    case no_personal_address_replace_assets_asset
    case no_trade_entries
    case not_enough_data
    case not_enough_money_on_balance
    case not_enough_money_on_balance_replace_asset
    case ok
    case old_password
    case old_password_lowercased
    case one_equals
    case one_equals_replace_base_asset
    case one_equals_replace_price
    case one_equals_replace_quote_asset
    case one_for
    case one_for_replace_base_asset
    case one_for_replace_quote_asset
    case one_for_replace_sale_invest_price_amount
    case open_app
    case operation
    case opportunities
    case opportunity_cancelation
    case opportunity_details
    case order
    case order_book_cap
    case order_price_cannot_be_less_than_or_equal_to_0
    case orders_cap
    case other
    case outgoing
    case overview
    case paid
    case password
    case password_has_been_successfully_changed
    case password_should_contain_at_least_characters
    case password_should_contain_at_least_characters_replace_minimal_length
    case passwords_dont_match
    case pay_recipients_fee
    case payment
    case payment_amount
    case payment_destination
    case payout
    case pending
    case pending_investment
    case pending_order
    case pending_order_details
    case pending_orders
    case percent
    case percent_colon
    case percent_fee
    case percent_funded
    case percent_funded_replace_percent
    case permission_denied
    case permissions_denied
    case personal_details
    case photo_verification
    case physical_price
    case please_validate_this_seed
    case policy
    case polls
    case price
    case price_colon
    case price_newline
    case price_newline_replace_quote
    case query_parameters_are_missing
    case quote_asset_is_not_found
    case quote_balance_is_not_found
    case receive
    case received
    case received_amount_may_be_lower_due_to_network_fees
    case received_amount_may_be_lower_due_to_network_fees_replace_destasset
    case recipient
    case recipients_email
    case recipients_fee
    case recipients_fee_has_been_paid
    case recover_it
    case recovery
    case recovery_seed
    case recovery_seed_is_copied_to_pasteboard
    case recovery_seed_lowercased
    case redeem
    case reference
    case register
    case register_now
    case rejected
    case reload
    case remove_vote
    case renew
    case repeat_title
    case request_error
    case request_error_replace_message
    case resend_email
    case sale
    case sale_details
    case sale_is_not_found
    case sales
    case sale_summary
    case save_this_seed_to
    case save_this_seed_to_replace_never
    case save_this_seed_to_replace_seed
    case save_this_seed_to_replace_we_do_not_know_your_seed
    case save_this_seed_to_x
    case scan_qr_code_via_authenticator
    case scan_server_info_qr_code
    case search
    case secret_seed
    case security
    case seems_like_some_fields_are_empty
    case select_asset
    case select_contact
    case select_file
    case selected_file
    case selected_file_replace_file_name
    case selfie_with_verification_code
    case sell
    case send
    case send_transaction_error
    case send_transaction_error_replace_message
    case sender
    case senders_email
    case sent
    case server
    case set_placeholder
    case set_up_2fa
    case settings
    case show_key
    case side_title
    case sign_in
    case sign_in_now
    case sign_in_via
    case sign_in_with_authenticator
    case sign_in_with_faceid
    case sign_in_with_touchid
    case sign_out
    case sign_out_and_erase
    case sign_up
    case signin
    case signing_in
    case since_last_period
    case since_last_period_replace_period
    case soft_cap
    case sold
    case source
    case source_replace_source
    case start_time
    case starts_in_days
    case starts_in_days_replace_days
    case state
    case subject
    case submit
    case submit_vote
    case subtype
    case success
    case success_parameter_is_missing_or_invalid
    case swift_bic
    case swift_bic_colon
    case terms_of_service
    case terms_of_service_not_agreed
    case terms_of_use
    case there_is_no_any_poll_for_chosen_asset
    case there_is_no_progress_history_yet
    case this_feature_will_be
    case this_seed_is_the_only_way
    case to
    case to_account
    case to_be_sure_document_key
    case to_enable_twofactor_authentication
    case to_enable_twofactor_authentication_replace_secret
    case to_make_a_deposit_send_to_this_address
    case to_make_a_deposit_send_to_this_address_replace_asset
    case to_pay
    case to_receive
    case to_replace_address
    case to_sell
    case tokend
    case total
    case total_colon
    case trade
    case trades
    case trades_cap
    case trades_header_amount_base
    case trades_header_amount_base_replace_asset
    case trades_header_price_quote
    case trades_header_price_quote_replace_asset
    case trades_header_time
    case transaction_details
    case twofactor_authentication
    case twofactor_authentication_failed
    case unable_to_encode_asset_to_data
    case unable_to_get_keychaindata_or_create_key_pair
    case unable_to_read_keychain_data
    case unable_to_read_user_data
    case unable_to_read_wallet_data
    case unable_to_sign_asset_data
    case unable_to_sign_tfa_asset_with_password
    case unathorized_request
    case unathorized_request_replace_message
    case undefined
    case unknown
    case unknown_error
    case unlocked
    case unsuitable_status
    case unsupported_version
    case unsupported_version_replace_function
    case unverified_account
    case update
    case upper_bound
    case up_to
    case up_to_replace_amount
    case userdataprovider_should_always_provide_walletdata
    case verification
    case verification_link_is_sent
    case verification_request_rejected
    case verification_request_rejected_permanently
    case verify_email
    case view_history
    case view_more
    case volume
    case wallet
    case we_do_not_know_your_seed
    case week
    case withdraw
    case withdraw_amount
    case withdraw_destination
    case withdrawal
    case withdrawn
    case wrong_email
    case wrong_old_password
    case wrong_password
    case year
    case yes
    case yesterday_at
    case yesterday_at_replace_hours
    case you_can_grant_permissions
    case you_have_already_invested
    case you_have_no_depositable_assets
    case your_account_is_approved
    case your_verification_request_is_submitted
}
