// This file is auto-generated

import Foundation

enum LocKey: String {
// swiftlint:disable identifier_name
    case access_revoked_sign_in_required
    case account
    case account_id
    case account_id_or_email_colon
    case acknowledgements
    case already_have_an_account
    case aml_alert_request
    case amount
    case amount_colon
    case amount_sent
    case amount_newline
    case amount_newline_replace_base
    case are_you_sure_you_want_to_sign_out
    case asset
    case asset_pair
    case at_date
    case at_date_replace_date
    case authenticator
    case available
    case available_date
    case available_date_replace_formatted
    case back
    case balance_colon
    case balance_is_not_created
    case balance_is_not_created_replace_asset
    case base_asset_for_hard_cap
    case base_for_price
    case base_for_price_replace_base_amount
    case base_for_price_replace_price_amount
    case bought
    case bounds
    case buy
    case buy_base
    case buy_base_replace_base
    case can_be_traded_on_secondary_market
    case cancel
    case cancel_tfa
    case canceled
    case cannot_be_traded_on_secondary_market
    case cannot_decode_original_account_id_data
    case cannot_derive_encoded_wallet_id
    case change_password
    case charged
    case charged_from_lock
    case choose_email
    case close_time
    case code
    case confirm
    case confirm_new_password
    case confirm_password
    case confirm_password_lowercased
    case confirmation
    case copied
    case copy
    case corrupted_keychain_data
    case create_balance
    case create_offer
    case dashboard
    case date
    case day
    case days_days
    case days_days_replace_days
    case days_left
    case deployed
    case deposit
    case description
    case description_optional
    case destination_address
    case done
    case dont_have_an_account
    case effect
    case email
    case email_address_is_not_verified
    case email_already_taken
    case email_lowercased
    case empty_amount
    case empty_recipient_address
    case empty_signers_data
    case ended
    case enter_account_id_or_email
    case enter_amount
    case enter_destination_address
    case enter_email
    case enter_f
    case enter_f_replace_field_name
    case enter_password
    case enter_password_confirmation
    case enter_recovery_seed
    case enter_t
    case enter_t_replace_title
    case erase_all_data_and
    case error
    case error_while_formatting_orderbookid
    case expires_at
    case expires_at_replace_date
    case explore_funds
    case explore_tokens
    case export_seed
    case failed
    case failed_to_build_kdf_params
    case failed_to_create_balance_for
    case failed_to_create_balance_for_replace_asset
    case failed_to_decode_account_id
    case failed_to_decode_account_id_replace_id
    case failed_to_decode_balance_id
    case failed_to_decode_balance_id_replace_id
    case failed_to_decode_base_balance_id
    case failed_to_decode_quote_balance_id
    case failed_to_encode_destination_address
    case failed_to_fetch_network_info
    case failed_to_generate_key_pair
    case failed_to_generate_new_key_pair
    case failed_to_generate_password_factor_key_pair
    case failed_to_generate_recovery_key_pair
    case failed_to_get_wallet_data
    case failed_to_load_fees
    case failed_to_load_fees_replace_message
    case failed_to_resolve_recipient_address
    case failed_to_resolve_recipient_address_replace_message
    case failed_to_save_account_data
    case failed_to_save_key_and_wallet_data
    case failed_to_save_network_info
    case failed_to_scan_server_info
    case fatal_error
    case fee
    case fee_error
    case fee_error_replace_message
    case fees
    case fixed
    case fixed_fee
    case for_code
    case for_code_replace_code
    case forgot_your_password
    case formatted_date
    case formatted_date_replace_date
    case from_account
    case funded
    case general
    case get_address
    case hard_cap
    case hour
    case i_agree_on_the
    case i_understand
    case incoming
    case incoming_outgoing
    case incorrect_or_corrupted_recovery_seed
    case input_2fa_code
    case input_code_from_google_authenticator_or_similar_app
    case input_code_sent_to_your_email
    case input_password
    case install_authenticator
    case insufficient_funds
    case invalid_account_id
    case invalid_account_id_or_email
    case invest
    case invested
    case invested_colored
    case invested_replace_amount
    case investing
    case investment
    case investment_cancellation
    case investment_details
    case investments
    case investors
    case investors_colored
    case investors_replace_count
    case is_not_restricted_by_current_price
    case is_not_restricted_by_physical_price
    case is_restricted_by_current_price
    case is_restricted_by_physical_price
    case issuance
    case issued
    case keychaindataprovider_should_always_provide_key
    case left_lowercased
    case locked
    case lower_bound
    case main_title
    case manage_asset_pair
    case matched
    case maximum
    case month
    case more_info
    case network_info_error
    case network_info_error_replace_message
    case new_password
    case new_password_lowercased
    case no_asks
    case no_assets_can_be_deposited
    case no_available_periods
    case no_balance
    case no_balances
    case no_bids
    case no_fees_to_overview
    case no_growth
    case no_investments
    case no_open_funds
    case no_payments
    case no_pending_offers
    case no_personal_address
    case no_personal_address_replace_assets_asset
    case no_token
    case no_tokens
    case not_enough_data
    case not_enough_money_on_balance
    case not_enough_money_on_balance_replace_asset
    case offer
    case old_password
    case old_password_lowercased
    case one_equals
    case one_equals_replace_quote_asset
    case one_equals_replace_price
    case one_equals_replace_base_asset
    case one_for
    case one_for_replace_base_asset
    case one_for_replace_quote_asset
    case one_for_replace_sale_invest_price_amount
    case open_app
    case order_price_cannot_be_less_than_or_equal_to_0
    case outgoing
    case overview
    case paid
    case password
    case passwords_dont_match
    case pay_recipients_fee
    case payment
    case payout
    case pending
    case pending_investment
    case pending_offer_details
    case pending_offer
    case pending_offers
    case percent
    case percent_fee
    case permission_denied
    case permissions_denied
    case physical_price
    case please_validate_this_seed
    case price
    case price_colon
    case price_newline
    case price_newline_replace_quote
    case query_parameters_are_missing
    case quote_asset_is_not_found
    case quote_balance_is_not_found
    case received
    case received_amount_may_be_lower_due_to_network_fees
    case received_amount_may_be_lower_due_to_network_fees_replace_destasset
    case recipient
    case recipients_fee
    case recover_it
    case recovery
    case recovery_seed
    case recovery_seed_is_copied_to_pasteboard
    case recovery_seed_lowercased
    case reference
    case register
    case register_now
    case rejected
    case reload
    case renew
    case repeat_title
    case request_error
    case request_error_replace_message
    case resend_email
    case sale
    case sale_details
    case sale_is_not_found
    case save_this_seed_in
    case save_this_seed_in_replace_seed
    case save_this_seed_in_x
    case scan_qr_code_via_authenticator
    case scan_server_info_qr_code
    case search
    case secret_seed
    case security
    case select_asset
    case select_contact
    case sell
    case sell_base
    case sell_base_replace_base
    case send
    case sender
    case send_transaction_error
    case send_transaction_error_replace_message
    case sent
    case server
    case set_placeholder
    case set_up_2fa
    case settings
    case side_title
    case sign_in
    case sign_in_now
    case sign_in_via
    case sign_in_with_authenticator
    case sign_in_with_faceid
    case sign_in_with_touchid
    case sign_out
    case sign_out_and_erase
    case sign_up
    case signin
    case signing_in
    case since_last_period
    case since_last_period_replace_period
    case soft_cap
    case sold
    case source
    case source_replace_source
    case start_time
    case starts_in
    case state
    case subject
    case subtype
    case success
    case success_parameter_is_missing_or_invalid
    case terms_of_service
    case terms_of_service_not_agreed
    case terms_of_use
    case this_feature_will_be
    case this_seed_is_the_only_way
    case to_account
    case to_enable_twofactor_authentication
    case to_enable_twofactor_authentication_replace_secret
    case to_make_a_deposit_send_to_this_address
    case to_make_a_deposit_send_to_this_address_replace_asset
    case to_pay
    case to_receive
    case to_sell
    case token
    case token_details
    case token_summary
    case tokend
    case total
    case total_colon
    case trade
    case trades
    case transaction_details
    case twofactor_authentication
    case twofactor_authentication_failed
    case unable_to_encode_token_to_data
    case unable_to_get_keychaindata_or_create_key_pair
    case unable_to_read_keychain_data
    case unable_to_read_user_data
    case unable_to_read_wallet_data
    case unable_to_sign_tfa_token_with_password
    case unable_to_sign_token_data
    case unathorized_request
    case unathorized_request_replace_message
    case undefined
    case unknown
    case unknown_error
    case unlocked
    case unsuitable_status
    case unsupported_version
    case unsupported_version_replace_function
    case upper_bound
    case userdataprovider_should_always_provide_walletdata
    case verification
    case verification_link_is_sent
    case verify_email
    case view_history
    case view_more
    case wallet
    case week
    case withdraw
    case withdrawal
    case withdrawn
    case wrong_email
    case wrong_old_password
    case wrong_password
    case year
    case you_can_grant_permissions
}
// swiftlint:enable identifier_name
