// This file is auto-generated

import Foundation

enum LocKey: String {
    
    case keychaindataprovider_should_always_provide_key
    case unsupported_version
    case unsupported_version_replace_function
    case access_revoked_sign_in_required
    case unathorized_request_replace_message
    case unathorized_request
    case fatal_error
    case sign_out
    case are_you_sure_you_want_to_sign_out
    case unable_to_read_user_data
    case unable_to_read_wallet_data
    case unable_to_read_keychain_data
    case userdataprovider_should_always_provide_walletdata
    case permissions_denied
    case you_can_grant_permissions
    case sign_out_and_erase
    case cancel
    case settings
    case error_unknown
    case ok_alert_action
    case signing_in
    case mediapicker_sourcetype_camera_title
    case mediapicker_sourcetype_documents_title
    case mediapicker_sourcetype_photolibrary_title
    case sign_in_title
    case sign_in_network_title
    case sign_in_login_title
    case sign_in_password_title
    case sign_in_forgot_password
    case sign_in_button
    case sign_in_use_local_key
    case sign_in_email_validation_error
    case sign_in_invalid_password_error
    case validation_error_empty
    case sign_up_title
    case next
    case done
    case fetch_network_info_error
    case passcode_authorization_error
    case authorization_error_wrong_login
    case sign_up_email_title
    case sign_up_password_title
    case sign_up_password_confirmation_title
    case sign_up_email_validation_error
    case sign_up_password_validation_error
    case sign_up_password_confirmation_validation_error
    case sign_up_create_account
    case sign_up_error_login_already_taken
    case tfa_code_title
    case tfa_code_placeholder
    case tfa_password_title
    case tfa_password_placeholder
    case touch_id_title
    case face_id_title
    case sign_out_button
    case more_tab_title
    case more_scene_title
    case more_deposit_title
    case more_withdraw_title
    case more_explore_sales_title
    case more_trade_title
    case more_polls_title
    case more_settings_title
    case more_user_blocked_status
    case more_user_corporate_status
    case more_user_general_status
    case more_user_unverified_status
    case no
    case yes
    case secret_seed_confirmation_title
    case secret_seed_confirmation_message
    case secret_seed_title
    case copy
    case change_password_title
    case change_password_current_password_title
    case change_password_new_password_title
    case change_password_confirm_new_password_title
    case change_password_password_placeholder
    case change_password_button
    case change_password_passwords_do_not_match
    case change_password_wrong_old_password_error
    case settings_title
    case settings_app_title
    case settings_app_language
    case settings_account_title
    case settings_account_account_id
    case settings_account_verification
    case settings_account_verification_description
    case settings_account_secret_seed
    case settings_account_secret_seed_description
    case settings_account_sign_out
    case settings_security_title
    case settings_security_lock_app
    case settings_security_tfa
    case settings_security_change_password
    case settings_tfa_wrong_code_error
    case tfa_setup_tfa
    case to_enable_two_factor_authentication
    case to_enable_two_factor_authentication_replace_secret
    case open_app
    case dashboard_title
    case send_asset_title
    case send_asset_continue
    case send_asset_recipient_title
    case send_asset_recipient_placeholder
}
